### ISSUE TITLE
AllowOnlineCreditCardPayment

### ISSUE THREAD

**Issue by ridwan-kazi** [ej2/python-quickbooks#158]
Do you guys support AllowOnlineCreditCardPayment on your Invoice class (I don't see it)? Its an optional field on Quickbooks API. I tried just tacking it on my invoice object, but I get an error when trying to .save.

**Comment by ej2** [comment]
It is not currently supported. It should be fairly easy to add. If you want to submit a PR, I will try to get it merged in soon.
