### ISSUE TITLE
PaymentMethod.to_ref() returns None instead of ref object

### ISSUE THREAD

**Issue by Janekk** [ej2/python-quickbooks#166]
missing return here: https://github.com/sidecars/python-quickbooks/blob/a202613998f364c263bb9d396b1f57a28a524919/quickbooks/objects/paymentmethod.py#L31

**Comment by ej2** [comment]
If you will submit a PR, I will merge it in. Thanks!

**Comment by ej2** [comment]
Fixed in version 0.8.2
