### ISSUE TITLE
simplejson optional

### ISSUE THREAD

**Issue by j-walker23** [ej2/python-quickbooks#167]
Hello, great lib. Super nice and easy.

Any chance `simplejson` dependency can be made optional, pretty please?

Apparently everything in my app uses `simplejson` if it exists, and I can't figure out the endless decode errors.

Thank you.

**Comment by ej2** [comment]
Not sure if that is possible. Maybe I can help with your problem. If you will add your error to this issue, I will take a look.

**Comment by j-walker23** [comment]
This was super confusing because the errors were happening in places I was already catching and sometimes expecting a `JSONDecodeError`.

Basically, none of my code places like below work anymore.
```
  from json import JSONDecodeError
  try:
    data = json.loads(data)
  except JSONDecodeError:
    pass
```
I would have to change them all to `simplejson.errors.JSONDecodeError`.

From my reading, `simplejson` is not used anymore in python3. And all major libs at most, make it optional.

Or remove it entirely.
https://github.com/psf/requests/issues/3052

**Comment by ej2** [comment]
Absolutely @pablogamboa.

**Comment by pablogamboa** [comment]
Sent a [PR](https://github.com/ej2/python-quickbooks/pull/358) that removes simplejson @ej2 added rationale in the PR description. PTAL 🙏
