### ISSUE TITLE
Feature -How to access Reporting Entity?

### ISSUE THREAD

**Issue by parvbhullar** [ej2/python-quickbooks#168]
Is it possible to access reporting entity?

**Comment by hyshka** [comment]
I haven't tried this out yet, but check here @parvbhullar:

https://github.com/sidecars/python-quickbooks/blob/3c066c93d1917f7c351f728a751980274e396cb0/quickbooks/client.py#L147

**Comment by judescripts** [comment]
> I haven't tried this out yet, but check here @parvbhullar:
> 
> https://github.com/sidecars/python-quickbooks/blob/3c066c93d1917f7c351f728a751980274e396cb0/quickbooks/client.py#L147

This works great. Thanks for the reference.
