### ISSUE TITLE
Cannot update Account

### ISSUE THREAD

**Issue by crkacer** [ej2/python-quickbooks#169]
Hello,
I was trying to update CurrentBalance of Account using this code, but seems not working. I also tried batch_update and Fault object is None, so it means no error, right?:

>        if partner_contribution_account:
>            partner_contribution_account.CurrentBalance = partner_contribution_account.CurrentBalance + amount
>        print(partner_contribution_account.to_json())
>        resp = partner_contribution_account.save(qb=client)
>        print(resp.to_json())

Here is what print out from these 2 print lines above :

> {
>    "AccountSubType": "PartnerContributions",
>    "AccountType": "Equity",
>    "AcctNum": "",
>    "Active": true,
>    "CurrencyRef": {
>        "name": "Canadian Dollar",
>        "type": "",
>        "value": "CAD"
>    },
>    **"CurrentBalance": 10000**,
>    "CurrentBalanceWithSubAccounts": 0,
>    "Description": "Clearing account for share purchases.",
>    "FullyQualifiedName": "1664 Simcoe Partner Contributions",
>    "Id": "64",
>    "MetaData": {
>        "CreateTime": "2019-10-22T14:06:16-07:00",
>        "LastUpdatedTime": "2019-10-22T14:20:08-07:00"
>    },
>    "Name": "1664 Simcoe Partner Contributions",
>    "SubAccount": false,
>    "SyncToken": "1",
>    "domain": "QBO",
>    "sparse": false
>}
>{
>    "AccountSubType": "PartnerContributions",
>    "AccountType": "Equity",
>    "AcctNum": "",
>    "Active": true,
>    "CurrencyRef": {
>        "name": "Canadian Dollar",
>        "type": "",
>        "value": "CAD"
>    },
>    **"CurrentBalance": 0**,
>    "CurrentBalanceWithSubAccounts": 0,
>    "Description": "Clearing account for share purchases.",
>    "FullyQualifiedName": "1664 Simcoe Partner Contributions",
>    "Id": "64",
>    "MetaData": {
>        "CreateTime": "2019-10-22T14:06:16-07:00",
>        "LastUpdatedTime": "2019-10-22T14:20:08-07:00"
>    },
>    "Name": "1664 Simcoe Partner Contributions",
>    "SubAccount": false,
>    "SyncToken": "1",
>    "domain": "QBO",
>    "sparse": false
>}

**Comment by CSviaCPA** [comment]
What is the value of the variable amount, and client? Also, what is the purposebehind creating the 'resp' variable and not just calling 'partner_contribution_account.CurrentBalance'?

**Comment by akaptur** [comment]
@crkacer , CurrentBalance is a read-only field on an account, so you can't update it through the API: https://developer.intuit.com/app/developer/qbo/docs/api/accounting/most-commonly-used/account

It makes sense that this field is read-only, because the balance on an account is calculated from the transactions in that account.

It would be helpful if QBO returned an error when you try to set this field, but the API will often silently ignore fields instead.
