### ISSUE TITLE
Catching Errors quickbooks.exceptions.QuickbooksException: Duplicate Name Exists Error

### ISSUE THREAD

**Issue by johnnydisco** [ej2/python-quickbooks#174]
Please can the instructions for catching errors be included in the docs.  I am not sure how to catch the error:

quickbooks.exceptions.QuickbooksException: Duplicate Name Exists Error

I have deliberately caused it for a test but I would like to catch a couple of the common examples..

**Comment by ej2** [comment]
I added a small section to the readme about QuickbookException.
