### ISSUE TITLE
Do I have to create AuthClient and QuickBooks objects each time I make a request?

### ISSUE THREAD

**Issue by allidoisace** [ej2/python-quickbooks#182]
The documentation provided shows AuthClient being used for every single request in the QuickBooks object. If I establish a connection through Open ID and store the related information, why do I have to create an AuthClient object each time I want to try and make a request? 

Unless I am missing something, this doesn't seem right at all.

**Comment by morenoh149** [comment]
looks like they init the client on every request https://github.com/IntuitDeveloper/SampleOAuth2_UsingPythonClient/blob/master/app/views.py I agree typically you init once and keep that in memory. Maybe submit a PR refactoring this? Maybe you'll figure out if there is technical reason for this.

**Comment by ej2** [comment]
You can re-use the AuthClient. Look through the integration tests for examples (https://github.com/ej2/python-quickbooks/tree/master/tests/integration)
