### ISSUE TITLE
Attach pdf to purchase order

### ISSUE THREAD

**Issue by pkochubey** [ej2/python-quickbooks#186]
Hi, we have any way to solved this issue? In UI you can attach file to PO, but not worked attaching through po.AttachableRef or attachable_ref.EntityRef =  [{'EntityRef': {'type': 'purchaseorder', 'value': "100"}}]

`  
  File "C:\Python38\lib\site-packages\quickbooks\objects\attachable.py", line 64, in save
    obj = type(self).from_json(json_data['AttachableResponse'][0]['Attachable'])
KeyError: 'Attachable'
`

**Comment by pkochubey** [comment]
attachable.AttachableRef = [{'EntityRef': {'type': 'PurchaseOrder', 'value': po.Id}}]

**Comment by cambiumproject** [comment]
@pkochubey How did you end up fixing this?
