### ISSUE TITLE
Product SKU's not found

### ISSUE THREAD

**Issue by shaikhmasud147** [ej2/python-quickbooks#188]
I am trying to get all product datails. All data is getting fine but sku is not getting. **None**.

**Comment by ej2** [comment]
Check to see if the Item has a sku (it is an optional field).

**Comment by baubie** [comment]
I see this was closed, but I believe this is a legit bug.  I have verified that my products have skus in the QBO UI, however, skus are not returned or accessible through this library.  @ej2 Were you unable to reproduce this?
