### ISSUE TITLE
CustomField not available for lookup

### ISSUE THREAD

**Issue by thismatters** [ej2/python-quickbooks#189]
I see that `CustomField`s are supported, but it does not seem there is a way to retrieve them from QBO, meaning that you have to know the id of the field in advance in order to use it. Is this intentional? 

For my use case it would be best to be able to look up a custom field by name.

**Comment by morenoh149** [comment]
is that like genericforeign keys? those typically use a contenttype id and a primary key for the related table.

**Comment by thismatters** [comment]
I don't think we're talking about the same thing. I'm referring to the [Quickbooks field called `CustomField`](https://developer.intuit.com/app/developer/qbo/docs/develop/tutorials/create-custom-fields#read-custom-fields) which can be used on an [Invoice](https://developer.intuit.com/app/developer/qbo/docs/api/accounting/most-commonly-used/invoice). 

There is a [class for them in this package](https://github.com/ej2/python-quickbooks/blob/bac499a9452636ebbc885952a5359674c4a0cc99/quickbooks/objects/base.py#L107), but it seems to just be a constructor and does not permit querying the QBO API for available resources.

**Comment by ej2** [comment]
You are correct @thismatters, the CustomField object is not wired up to load the data returned from a query.  Not sure when this will get added.

**Comment by thismatters** [comment]
@KoffieOmar The only way I know is to retrieve a resource which has had the custom field set (via the frontend) and introspect the field ID from the data.
