### ISSUE TITLE
CountryCurrency don't work

### ISSUE THREAD

**Issue by muglanov** [ej2/python-quickbooks#193]
Getting CountryCurrency values by all ways, for example:
`CountryCurrency.all(qb=client)`
or
`CountryCurrency.get(id, qb=client)`
leads to
```
File "/usr/local/lib/python3.7/dist-packages/quickbooks/mixins.py", line 101, in get
    return cls.from_json(json_data[cls.qbo_object_name])
File "/usr/local/lib/python3.7/dist-packages/quickbooks/mixins.py", line 33, in from_json
    sub_obj = sub_obj.from_json(json_data[key])
AttributeError: 'MetaData' object has no attribute 'from_json'
```

Everything works, if delete this line:
https://github.com/ej2/python-quickbooks/blob/bac499a9452636ebbc885952a5359674c4a0cc99/quickbooks/objects/companycurrency.py#L16

**Comment by ej2** [comment]
Fixed in 0.8.3 - https://github.com/ej2/python-quickbooks/releases/tag/0.8.3
