### ISSUE TITLE
Missing Contributing Guide

### ISSUE THREAD

**Issue by HaddadJoe** [ej2/python-quickbooks#195]
It's a bit confusing to contribute to this repo without a contributing guide. What are the standard way for creating PRs, running tests, any other steps to be taken before opening a pull request ?

Would be very helpful if there was a contributing guide with clear instructions

Great work, very helpful repo, thanks!

**Comment by ej2** [comment]
I have added a contribution guide. It has some information on testing. Hope it helps.
https://github.com/ej2/python-quickbooks/blob/master/contributing.md
