### ISSUE TITLE
invoiceLink can be included or retrieved for an Invoice

### ISSUE THREAD

**Issue by bryanfarris** [ej2/python-quickbooks#198]
Per the quickbooks API documentation:

InvoiceLink

String
Sharable link for the invoice sent to external customers. The link is generated only for invoices with online payment enabled and having a valid customer email address. Include query param `include=invoiceLink` to get the link back on query response.

Currently:
Invoice objects returned do not have a way to include invoiceLink

Expected/Goal:
Add method to retrieve invoiceLink for a given invoice object.

**Comment by ej2** [comment]
InvoiceLink was added in version 0.8.4.
