### ISSUE TITLE
[Q] How to create CreditCardPayment ?

### ISSUE THREAD

**Issue by jakubczaplicki** [ej2/python-quickbooks#201]
I need to create a CreditCardPayment and I am a bit confused how to do it using the library.

The [API doc](https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/creditcardpayment])  says that I in order to create `CreditCardPayment` only need `TxnDate` , `Amount` , `BankAccountRef` and `CreditCardAccountRef` . However looking at the code of the lib, it seems that I need to first create a `Payment` object which requires more data and takes `CreditCardPayment` as sub argument (?).

Is creating `Payment` object the way to create `CreditCardPayment` ? Or is the CreditCardPayment not implemented in the library ?

**Comment by jakubczaplicki** [comment]
PR #202

**Comment by ej2** [comment]
Added in version 0.8.4
