### ISSUE TITLE
TxnDate is missing for Invoice

### ISSUE THREAD

**Issue by wowkin2** [ej2/python-quickbooks#204]
In [QBO Invoice documentation](https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/invoice#create-an-invoice), I see
> TxnDate (Optional) - Date _, filterable , sortable_

But I don't see it in Invoice class of [invoice.py](https://github.com/ej2/python-quickbooks/blob/master/quickbooks/objects/invoice.py). But [Bill class have it](https://github.com/ej2/python-quickbooks/blob/master/quickbooks/objects/bill.py#L47).

Is it a typo? Or did I missed anything?
P.S. Probably there are other fields that are missing.

**Comment by ej2** [comment]
`TxnDate` was probably added to Invoice in a minor version after the original object was created. If you would like to submit a pull request adding that and any other missing fields, I will try to get it merged in soon.

**Comment by wowkin2** [comment]
@ej2 should I update version to `0.8.5` or `0.9.0`?
Or you plan to do that later with some next release?

**Comment by ej2** [comment]
@wowkin2 I will update the version when I build the next release.

**Comment by wowkin2** [comment]
@ej2 any estimate for that?

**Comment by wowkin2** [comment]
Created another PR #209 with base from feature-branch, not `master`.

**Comment by ej2** [comment]
Sorry it has taken so long to get this merge in.
