### ISSUE TITLE
Return results when object is saved

### ISSUE THREAD

**Issue by dansolomo** [ej2/python-quickbooks#205]
It would be really helpful for UpdateMixin to return json_data for integration use cases where records, such as customers and invoices, can be synchronized with another system.

Any thoughts?

**Comment by ej2** [comment]
The save method on the UpdateMixin returns the updated object. If you need the json data, you can call `to_json` on that object. Example here: [https://github.com/ej2/python-quickbooks#working-with-json-data](https://github.com/ej2/python-quickbooks#working-with-json-data)

**Comment by dansolomo** [comment]
@ej2 thanks.  That was it.  I should have been able to figure that out myself.  I'm liking this.
