### ISSUE TITLE
Ambiguous behavior in QuickbooksException

### ISSUE THREAD

**Issue by DanilXO** [ej2/python-quickbooks#207]
Hello! I am creating the integration with Quickbooks and I decided to use your library, but I encountered an ambiguous QuickbooksException behavior when making requests. error_code attribute is always == 0
![image](https://user-images.githubusercontent.com/16720007/100573411-2b4e7000-32f1-11eb-83b7-e27b5c613871.png)

**Comment by ej2** [comment]
Authentication failed because the `Token expired`. You can read over the [OAuth 2.0 guide](https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization/oauth-2.0) for more details.

**Comment by ej2** [comment]
Oh... wait I read that wrong. You are saying that it should have set `error_code` but it didn't. Not sure what is happening yet. I will have to dig into that one. I am reopening the issue. Again, sorry for the confusion.

**Comment by HarmonizeL** [comment]
Has this been resolved? 
<img width="522" alt="Screen Shot 2020-12-13 at 2 55 21 PM" src="https://user-images.githubusercontent.com/74299900/102022225-63bf6680-3d53-11eb-9922-86b6e4bb5e51.png">

I am simplifying this for my own understanding as I am new to python and am working on an app that only I will be using. I have filled my client Id/secret; exchanged out the return for the URI and have used Webbrowser (this works to run the Redirect URI). I then manually fill the Auth Code and Realm ID. I know these are working, as the get bearer token process works and allows me to retrieve the access token /refresh token.
<img width="549" alt="Screen Shot 2020-12-13 at 2 59 13 PM" src="https://user-images.githubusercontent.com/74299900/102022285-cdd80b80-3d53-11eb-9df5-929bdefae598.png">
I think define the "client" as directed but when I run the first simple command (retrieve list of customers), I get the same "Application Authentication Failed" error message as discussed above.

**Comment by DanilXO** [comment]
@HarmonizeL 
This issue about that all custom exceptions have field error_code and it is field always equal 0. This is unexpected behavior.
Your problem in OAuth. You can read over the [OAuth 2.0 guide](https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization/oauth-2.0) for more details or you can try oficial [examples](https://github.com/IntuitDeveloper/SampleOAuth2_UsingPythonClient/blob/master/app/views.py).

**Comment by DanilXO** [comment]
@ej2 
![image](https://user-images.githubusercontent.com/16720007/102058498-038afc00-3e09-11eb-8377-4586f72a4204.png)
I solved my problem using a decorator, since the type of exception define correctly, but I think that setting error_code should be fixed, or This field should be removed so as not to confuse people.

**Comment by MahmudulHassan5809** [comment]
@DanilXO hello can help me please. i am also facing this problem I want to update the access token if expired using a refresh token. Bur don't implement the logic.

**Comment by DanilXO** [comment]
@MahmudulHassan5809 Unfortunately, I no longer work for the company for which I did this integration and do not have access to the code. You can implement this yourself. The above hack solves this issue's problem. If you have problems updating the token, you should create a new issue.

**Comment by MahmudulHassan5809** [comment]
@DanilXO Thanks for your response. Actually token is updated. But i want to update automatically when it required. 
Can you please give me some hint or any help please.

**Comment by DanilXO** [comment]
@MahmudulHassan5809 I used a regular cron to update the token (and indeed for similar tasks) If this is django, then you can look at [django-cron](https://django-cron.readthedocs.io/en/latest/index.html)

**Comment by DanilXO** [comment]
As far as I can see, the problem has not been resolved, so I have no right to close the issue. Although this is no longer relevant for me.

**Comment by ej2** [comment]
I think I discovered the issue. The client handles 401 response status code outside of the `handle_exceptions` function. I will add the status code when raising `AuthorizationException` in the `make_request` function. Look for this in the next release.

**Comment by ej2** [comment]
Fixed in version `0.9.1`
