### ISSUE TITLE
Update TaxRate?

### ISSUE THREAD

**Issue by ruby232** [ej2/python-quickbooks#213]
I create TaxRate with TaxService:
```python  
  qb_object = TaxService()
  qb_object.TaxCode = 'TEST'  
  qb_object.TaxRateDetails = [{
      "RateValue": '10',
      "TaxAgencyId": "1",
      "TaxRateName": 'TEST'
  }]
  qb_object.Active = True
  qb_object = qb_object.save(qb=self.qb_client)
```
this work fine.

Now I want to update the RateValue, but I can't find how to do it.

TaxService not have search method for get from QB and save new value.
TaxRate not have method save.

This is problem of the library or QB not allow edit TaxRate?

**Comment by ej2** [comment]
[TaxService](https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/taxservice) and [TaxRate](https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/taxrate) do not have update endpoints on the Quickbooks API.
