### ISSUE TITLE
[HELP] Upload attachment to an invoice

### ISSUE THREAD

**Issue by jalilrooney** [ej2/python-quickbooks#215]
Hello everyone!

I'm new to quickbooks and I want to upload an attachment to quickbooks using this library, there is an example for employers here but not invoices.

so I would really appreciate any help!

Thanks a lot

**Comment by ej2** [comment]
It should work the same as customers or employers. Just change the  `EntityRef` on the AttachableRef to point to your Invoice. Like so:
```
attachment = Attachable()

attachable_ref = AttachableRef()
attachable_ref.EntityRef = invoice.to_ref()  # This is where to attach the invoice

attachment.AttachableRef.append(attachable_ref)

attachment.FileName = 'Filename'
attachment._FilePath = '/folder/filename'  # full path to file
attachment.ContentType = 'application/pdf'
attachment.save(qb=client)
```

**Comment by ahmadberkeleypayment** [comment]
How do we add an attachment that is uploaded to Quickbooks Online. I have the attachment Id.

**Comment by ej2** [comment]
I am not sure the Quickbooks API supports that.
