### ISSUE TITLE
TaxService update is not working

### ISSUE THREAD

**Issue by navneetgarggate6** [ej2/python-quickbooks#225]
I am trying to update tax service. I passed TaxCodeId but getting error.

```
    taxServiceObj = TaxService()
    taxServiceObj.TaxCode= "test1"
    taxServiceObj.TaxCodeId = 9
    taxRateDetail = TaxRateDetails()
    taxRateDetail.TaxRateName = "test1"
    taxRateDetail.RateValue = "10"
    taxRateDetail.TaxAgencyId = "1"
    taxRateDetail.TaxApplicableOn = "Sales"  
    taxServiceObj.TaxRateDetails.append(taxRateDetail)
    taxServiceResponseData = taxServiceObj.save(client)
    print(taxServiceResponseData.to_json())
```
But getting Duplicate Name Exists Error

**Comment by ej2** [comment]
I would guess there is another record with the TaxCode value of "test1".  You can get the same error if you try creating multiple TaxServices with the API Explorer (https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/taxservice)
