### ISSUE TITLE
Incompatibility issue with intuit_oauth

### ISSUE THREAD

**Issue by promitbasak** [ej2/python-quickbooks#226]
I am newly using this package, and recently saw a new version of `intuit-oauth` was available more than a year ago and is incompatible with `python-quickbooks 0.8.4` according to pip: 
```
python-quickbooks 0.8.4 has requirement intuit-oauth==1.2.3, but you'll have intuit-oauth 1.2.4 which is incompatible.
```

**Comment by ej2** [comment]
Fixed in version 0.9
