### ISSUE TITLE
Does it generate a new access token for every request?

### ISSUE THREAD

**Issue by MahmudulHassan5809** [ej2/python-quickbooks#230]
Does it generate a new access token for every request?

Here in every request  **self.auth_client.access_token**  is None.So it generates the access token every time.
```
  def _start_session(self):
        if self.auth_client.access_token is None:
            self.auth_client.refresh(refresh_token=self.refresh_token)

        self.session = OAuth2Session(
            client_id=self.auth_client.client_id,
            client_secret=self.auth_client.client_secret,
            access_token=self.auth_client.access_token,
        )
```
I have stored the access token and refresh token. As QuickBooks documentation after 60 minutes, we should use the refresh token to get the new access token but here every time we use the refresh token. Please help me maybe my understanding is not correct.
Can you please help me to understand how to use the access token and refresh token with this package.

**Comment by ej2** [comment]
This library calls refresh on the `auth_client` if the `access_token` is missing. You can (and probably should) pass the `access_token` into the AuthClient like so:

```
self.auth_client = AuthClient(
  client_id='CLIENT_ID',
  client_secret='CLIENT_SECRET',
  environment='SANDBOX',
  access_token='ACCESS_TOKEN'
)
```

You can see more examples of this in Intuit OAuth samples: [https://github.com/IntuitDeveloper/SampleOAuth2_UsingPythonClient](https://github.com/IntuitDeveloper/SampleOAuth2_UsingPythonClient)

I will make a note about passing in the `access_token` on the readme.

**Comment by MahmudulHassan5809** [comment]
Yup i have  already figured it. Thanks

**Comment by daniel-butler** [comment]
This was a great call-out! Putting this in the readme helped me handle the refresh and access tokens early on.
