### ISSUE TITLE
Missing ExchangeRate Object

### ISSUE THREAD

**Issue by PASR8** [ej2/python-quickbooks#232]
Just wondering if you'd be able to add the ExchangeRate object to the repository.  I have created one myself by copying and modifying the CompanyCurrency object but I would like to see it incorporated into the build if possible.

I can send you what I've done if that helps but it probably warrants a review by someone more familiar with the existing code / design.

Thanks for your consideration.

ps

**Comment by ej2** [comment]
Done. Added in version 0.9.

**Comment by PASR8** [comment]
Thanks very much.
