### ISSUE TITLE
AttributeError: 'CompanyInfo' object has no attribute 'save'

### ISSUE THREAD

**Issue by PASR8** [ej2/python-quickbooks#236]
You currently have CompanyInfo defined as a QuickbooksReadOnlyObject.  The API Documentation states that the CompanInfo object is updateable as of Minor Version 11.

Changing the class definition to QuickbooksManagedObject and QuickbooksTransactionEntity appears to resolve this; I believe they're both required but I'm not sure if there are any potential issues from implementing it this way.

**Comment by ej2** [comment]
Fixed in 0.9.2
