### ISSUE TITLE
Request for filter method to accept > and < operators.

### ISSUE THREAD

**Issue by Sticky-Bits** [ej2/python-quickbooks#237]
Hey, quick feature request.

I'd be awesome if the `object.filter` method could accept a double underscored `__gt` or `__lt` suffix on parameters to allow use of > and < without resorting to the `query` method. Basic queries of "Get me all invoices updated after x date" basically require writing your own sql at the moment.

Suggested that [this method](https://github.com/ej2/python-quickbooks/blob/715ae3f6d2ac435159d288b33d2a347e335601fd/quickbooks/utils.py#L5) should split kwargs on double underscore and check for the presence of `gt` or `lt` and construct the appropriate sql.

Here's an example of how pyxero does it: [boop](https://github.com/freakboy3742/pyxero/blob/4630e4e8538cd527db3932b224d5359ffc1cd7fd/xero/basemanager.py#L409)

Happy to submit a PR for this when I get some time, but also curious how important the `six` logic is for python2, since this library is stated to be "A Python 3 library".

Cheers.

**Comment by jarekwg** [comment]
Hey @ej2,

Was this implemented?
Issue was marked as closed, but I can't see where the functionality has been added.

Cheers,

**Comment by ej2** [comment]
It was not implemented. I closed it while cleaning up old issues. If someone would like to add this functionality I will review and merge it.
