### ISSUE TITLE
AccountBasedExpenseLineDetail missing initialization of ClassRef

### ISSUE THREAD

**Issue by tysonmoore1100** [ej2/python-quickbooks#238]
The AccountBasedExpenseLineDetail class doesn't initialize the ClassRef as None.  Below is the suggested updated code:

`class AccountBasedExpenseLineDetail(QuickbooksBaseObject):
    class_dict = {
        "CustomerRef": Ref,
        "AccountRef": Ref,
        "TaxCodeRef": Ref,
        "ClassRef": Ref,
        "MarkupInfo": MarkupInfo,
    }

    def __init__(self):
        super(AccountBasedExpenseLineDetail, self).__init__()
        self.BillableStatus = None
        self.TaxAmount = 0
        self.TaxInclusiveAmt = 0

        self.CustomerRef = None
        self.AccountRef = None
        self.TaxCodeRef = None
        self.ClassRef = None

    def __str__(self):
        return self.BillableStatus`

**Comment by ej2** [comment]
Thanks! I will get this change in the next release.
