### ISSUE TITLE
quickbooks-cli

### ISSUE THREAD

**Issue by bitmodeler** [ej2/python-quickbooks#240]
What happened to quickbooks-cli?

```
Traceback (most recent call last):
  File "/usr/local/bin/quickbooks-cli", line 6, in <module>
    from quickbooks.tools.cli import cli_execute
ModuleNotFoundError: No module named 'quickbooks.tools'
```

**Comment by ej2** [comment]
It was removed in version `0.8.0`. See: https://github.com/ej2/python-quickbooks/releases/tag/0.8

**Comment by bitmodeler** [comment]
Thought it might have been; just was odd that there was no specific mention of it being deprecated (that list you point to just shows general functionality changes, not that the utility was given a burial at sea...)
