### ISSUE TITLE
create a biil

### ISSUE THREAD

**Issue by qadir1020** [ej2/python-quickbooks#249]
Anyone knows how to create a bill for vendor using quickbooks python sdk?

**Comment by qadir1020** [comment]
@ej2

**Comment by ej2** [comment]
You can look at the [test code](https://github.com/ej2/python-quickbooks/blob/master/tests/integration/test_bill.py) as an example and see the [official docs](https://developer.intuit.com/app/developer/qbo/docs/api/accounting/most-commonly-used/bill) for required fields, etc
