### ISSUE TITLE
Example of handling invalid access token/generating new tokens

### ISSUE THREAD

**Issue by akhawaja2** [ej2/python-quickbooks#254]
Hi all, I'm new to the QBO/OAuth authentication process and wondering what the best practice is for checking /generating a new access token when it is invalid

When the access token fails is it as simple as checking for the 400 - invalid grant and generating a new one? Can I just throw my initial auth_client connection into a try/catch block and be ok? I've tried a few things and none seemed to be successful.

For reference I'm running a script that I'd like to run daily automatically (after manually generating the first refresh token in the playground), and have it generate everything on the fly as needed on subsequent QBO API accesses.

Thanks!

**Comment by varunbheemaiah** [comment]
I put the access token into cache with a timeout of one day shorter than however long it takes to expire and I have a function that uses the refresh token to generate a new access token whenever there isn't an access token in the cache. You can also do the same thing in MongoDB using a TTL index if you would rather store your keys in a DB

**Comment by jaredthecoder** [comment]
Sadly, this is one of the things that Intuit handles super poorly. However, there are tons of documents + forum posts on the developer help forums. What we do is only ask for a new access token when it explicitly expires, and when we do, we always save the new access token AND the refresh token. This way we never have an invalid refresh token.

@ej2 I recommend closing this as the Python Intuit-OAuthlib library discusses this.
