### ISSUE TITLE
SalesTermRef attribute not present on Invoice class

### ISSUE THREAD

**Issue by dantebarba** [ej2/python-quickbooks#267]
Hi,

I was checking the Invoice class and I've noticed that there is no attribute for SalesTermRef. The SalesTermRef should be available in the Invoice as per API-Specs.

![image](https://user-images.githubusercontent.com/6656541/151438140-94ff1fb6-1ef0-492e-8f1b-92c58fcd2d66.png)

Source: https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/invoice

I had to use something like this to patch it:

```python
setattr(invoice, "SalesTermRef", {"value": "2"})
```

**Comment by ej2** [comment]
Fixed in 0.9.2
