### ISSUE TITLE
No object for RecurringTransaction API

### ISSUE THREAD

**Issue by bdsoha** [ej2/python-quickbooks#270]
Hello,

Any plans to implement the functionality representing a `RecurringTransaction`?

https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/recurringtransaction

**Comment by chrisnicholls** [comment]
FYI I created a PR to add support for RecurringTransaction - https://github.com/ej2/python-quickbooks/pull/285

**Comment by bdsoha** [comment]
@chrisnicholls Thanks for the update. You should add a line to your main description with the word *"Closes: #270"* as to link the PR with this issue and automatedly close it upon merge.
