### ISSUE TITLE
Back / pylint / flake8

### ISSUE THREAD

**Issue by pvizeli** [ej2/python-quickbooks#277]
Hi @ej2 

Is that an option to contribute CI helpers for github actions including better and automated code quality:
- Black
- pylint
- flake8

For this project?

**Comment by ej2** [comment]
Sure thing!

**Comment by pvizeli** [comment]
You have pip installer and pip files in this repository which does not make sense to have in a project like this. Can I also clean that to prevent black/lint issues on unnecessary files?

**Comment by pvizeli** [comment]
Do you want also to add secrets for real API tests or only run the unit test without a real connection?

**Comment by ej2** [comment]
Probably not. Just run the unit test.
