### ISSUE TITLE
Query transactions, filtered by date range

### ISSUE THREAD

**Issue by PeteLambert89** [ej2/python-quickbooks#288]
Hi there,

I'm trying to figure out the SDK.

I'm attempting to query expenses for a business. Ideally filtered by a date range, and by expense type.

But I can't find a "Transaction" or "Expense" object... I assume I'm missing something obvious but I've been poring over the code to no avail.

Any help is appreciated!

Thanks,

**Comment by chrisnicholls** [comment]
You probably want the Purchase object. I’m typing this on mobile so might have something off but it would look something like:

``` from quickbooks.objects.purchase import Purchase

purchases = Purchase.where(“TxnDate >= ‘2022-12-01’”, qb=client)```

**Comment by PeteLambert89** [comment]
Thanks! Awesome.

On Dec 18, 2022, at 5:34 PM, Chris Nicholls ***@***.***> wrote:

﻿

You probably want the Purchase object. I’m typing this on mobile so might have something off but it would look something like:


purchases = Purchase.where(“TxnDate >= ‘2022-12-01’”, qb=client)```
