### ISSUE TITLE
Delete customer

### ISSUE THREAD

**Issue by jephrati** [ej2/python-quickbooks#289]
Hi! Awesome project that you all put together!
I wanted to delete a customer but have not been successful. I tried:
- the batch delete command
- Make the customer inactive (setting does not stick after end of run...), then tried to use batch delete command

Is there a command line that you know of that would delete a customer? Or to make it inactive, and have it stick?
Also, do you have a Telegram/Discord channel for additional questions?

**Comment by ej2** [comment]
[Customers](https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/customer) cannot be deleted. Customers do have an **active** field, you could set to false.

I do not have a Telegram/Discord channel. I do not work for Intuit. This is a project I started for my last job. I maintain it in my free time.
