### ISSUE TITLE
batch_delete operation is not supported by quickbooks api

### ISSUE THREAD

**Issue by depotalyssa** [ej2/python-quickbooks#294]
I have been attempting to add customers and then deleting them using the  `batch_delete` funciton. It gives me the Unsupported Operation error. 

These two links state that deleting an object using the api is not allowed. 

[one](https://help.developer.intuit.com/s/question/0D54R00007FFXoZSAX/is-it-possible-to-delete-a-customer-through-the-api-through-the-web-interface-i-can-mark-customers-inactive-but-i-would-like-to-permanently-delete-customers-if-possible-through-the-api)
[two](https://help.developer.intuit.com/s/question/0D54R00007Qz2QrSAJ/why-you-cannot-delete-a-customer)

deletion function:
![image](https://user-images.githubusercontent.com/122314418/223292465-797f4940-b6f8-4040-86f2-cd2fb45ea1d6.png)

output:
![image](https://user-images.githubusercontent.com/122314418/223292506-124df10a-ee54-48c9-8bb6-42b1f21d4147.png)

 I am using this inside pytests in order to add a test user and delete it from qbo once I am finished testing.

If there isn't an issue and I am just missing something, please let me know. I can't find anything else in the documentation on why I wouldn't be able to delete customer objects

**Comment by ej2** [comment]
D'oh! Deleting customers is not possible. I was using customer as an example in the docs and failed to check to see if it was possible. Thanks for pointing that out. I will get the docs updated.

**Comment by depotalyssa** [comment]
Thank you!
