### ISSUE TITLE
Using ToLinkedTxn with payments for invoices 

### ISSUE THREAD

**Issue by jacquilevitan** [ej2/python-quickbooks#296]
I'm trying to find what invoice the payment I submitted goes to. I would expect `toLinkedTxn` to do this for me, but instead of returning an invoice ID and the TxnType as "Invoice", I'm getting back information about the Payment. Is this expected behavior? Is there any way to see what invoice this payment is associated with??

**Comment by jasonhoward64** [comment]
I could be wrong, but it might be best to store this relationship in your database at the time that you submit the payment to QBO.

**Comment by ej2** [comment]
That data should be part of the payment. If you check the example Payment on the [QBO Docs](https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/payment) you will see a Line with a LinkedTxn that points to an invoice. 

As for `to_linked_txn` that returns a `linkedTxn` object that can be used to tie things together.
Example:

```
   invoice = Invoice.get(1, qb=client)
   line = PaymentLine()
   line.LinkedTxn.append(invoice.to_linked_txn())
```
