### ISSUE TITLE
Querying objects by nested fields

### ISSUE THREAD

**Issue by jasonhoward64** [ej2/python-quickbooks#298]
I'm attempting to query for a Payment that relates to a given Invoice Id.

eg. 
payments = Payment.filter(LinkedTxn__TxnId="10", qb=client)

This syntax doesn't work, but I'm wondering if this is possible and if so, how would it be done? Could you be able to add this to the readme?

Thanks Edward!

**Comment by ej2** [comment]
It's a great idea but I don't think QBO can handle that. `LinkedTxn` is on  PaymentLine and the QBO API doesn't let you query it. It also doesn't support JOIN or GROUP BY causes ([see here](https://developer.intuit.com/app/developer/qbo/docs/learn/explore-the-quickbooks-online-api/data-queries)).

**Comment by jasonhoward64** [comment]
Ok, thanks Edward! I appreciate the quick response on this!
