### ISSUE TITLE
Add the ability to void all voidable QB types

### ISSUE THREAD

**Issue by djpeach** [ej2/python-quickbooks#304]
Currently, the [VoidMixin](https://github.com/ej2/python-quickbooks/blob/master/quickbooks/mixins.py#L127) is built to be able to void Invoices and uses the `operation=void` param. When it comes to voidable types in QB, we have

* Payment
* SalesReceipt
* BillPayment
* Invoice

Here, Invoice is actually the exception, not the rule. For the first three types, you void them with an `operation=update` and `inlcude=void` params. Invoice is the only one that uses the `operation=void` param. 

So currently, the VoidMixin only works for Invoices, and the [Payment type has a special `void` method](https://github.com/ej2/python-quickbooks/blob/master/quickbooks/objects/payment.py#L87) with this one-off functionality, added by [ZedObaia](https://github.com/ZedObaia) to fix his [issue on voiding Payments](https://github.com/ej2/python-quickbooks/issues/247). The other types are not voidable without custom code like

```
def void_receipt(receipt_id: str) -> bool:
    qb = get_client()
    receipt = QBObjects.SalesReceipt()
    sparse_update_data = {
        "Id": receipt_id,
        "SyncToken": 0,
        "sparse": True
    }
    try:
        endpoint = receipt.qbo_object_name.lower()
        url = "{0}/company/{1}/{2}".format(qb.api_url, qb.company_id, endpoint)
        qb.post(url, json.dumps(sparse_update_data), params={"include": "void"})
        return True
    except:
        log.exception(f"Failed to void receipt {receipt_id}")
        return False
```

I would propose then that the VoidMixin be updated to use the `operation=update` and `inlcude=void` params and that the Invoice type should be the only one to have it's own special `void` method with this one-off functionality that uses the `operation=void` param.

**Comment by djpeach** [comment]
Revisiting this. Instead of a breaking change as suggested above, perhaps the mixin can detect the type and use the appropriate params. Is there any interest in this?

**Comment by ej2** [comment]
Absolutely. If you want to submit a PR, I will get it merged in.

**Comment by ZedObaia** [comment]
@djpeach Let me know if you need some help with that, I can give it a go
