### ISSUE TITLE
TaxInclusiveAmt is set to 0 despite a non-zero response from the QBO API

### ISSUE THREAD

**Issue by jaredthecoder** [ej2/python-quickbooks#311]
When fetching an AccountBasedExpenseLineDetail, the TaxInclusiveAmount is set to 0 due to this line https://github.com/ej2/python-quickbooks/blob/master/quickbooks/objects/detailline.py#L118, despite the API explorer returning a non-zero value.

See below screenshots:

I have my debugger open on the line right after calling the CDC API through the library, to illustrate the issue.

<img width="1331" alt="Screenshot 2023-07-28 at 17 45 07" src="https://github.com/ej2/python-quickbooks/assets/7459310/19157a15-786c-4dfd-abe6-7db5c3aaec65">
<img width="592" alt="Screenshot 2023-07-28 at 17 45 00" src="https://github.com/ej2/python-quickbooks/assets/7459310/beda5a0e-7804-44ef-a2d8-8ad82f0df34b">

**Comment by jaredthecoder** [comment]
Hmm, upon further investigation, it looks like this may be a result of the minor version string, but will need to look further.

**Comment by ej2** [comment]
Going to close this issue. If you discover a problem, feel free to reopen this issue.
