### ISSUE TITLE
"self.MarkupInfo" missing in  AccountBasedExpenseLineDetail class

### ISSUE THREAD

**Issue by xqtive** [ej2/python-quickbooks#313]
"self.MarkupInfo" missing in  AccountBasedExpenseLineDetail class. 

Is this intentional?

**Comment by ej2** [comment]
Not sure what you are talking about. [MarkupInfo](https://github.com/ej2/python-quickbooks/blob/9d7e4a5379b06c395e12791a50e6f2f23c3fd271/quickbooks/objects/detailline.py#L174C34-L174C34) is defined on  AccountBasedExpenseLineDetail. You might need to set the minor version in order for QBO to return the value.
