### ISSUE TITLE
'MarkupInfo' not initialize in AccountBasedExpenseLineDetail class

### ISSUE THREAD

**Issue by xqtive** [ej2/python-quickbooks#315]
I have double checked. MarkupInfo is defined inside class_dict, but is not initialize. Not like ItemBasedExpenseLineDetail class. Is this intentional or the initialization is just missing? The comparison of both class below:

`class ItemBasedExpenseLineDetail(QuickbooksBaseObject):
    
    class_dict = {
        "ItemRef": Ref,
        "ClassRef": Ref,
        "PriceLevelRef": Ref,
        "TaxCodeRef": Ref,
        "CustomerRef": Ref,
        "MarkupInfo": MarkupInfo
    }

    def __init__(self):
        super(ItemBasedExpenseLineDetail, self).__init__()
        self.BillableStatus = None
        self.UnitPrice = 0
        self.TaxInclusiveAmt = 0
        self.Qty = 0
        self.ItemRef = None
        self.ClassRef = None
        self.PriceLevelRef = None
        self.TaxCodeRef = None
        self.MarkupInfo = None
        self.CustomerRef = None`

`
class AccountBasedExpenseLineDetail(QuickbooksBaseObject):
    
    class_dict = {
        "CustomerRef": Ref,
        "AccountRef": Ref,
        "TaxCodeRef": Ref,
        "ClassRef": Ref,
        "MarkupInfo": MarkupInfo,
    }

    def __init__(self):
        super(AccountBasedExpenseLineDetail, self).__init__()
        self.BillableStatus = None
        self.TaxAmount = 0
        self.TaxInclusiveAmt = 0

        self.CustomerRef = None
        self.AccountRef = None
        self.TaxCodeRef = None
        self.ClassRef = None

    def __str__(self):
        return self.BillableStatus
`

as you can see MarkupInfo is not initialize AccountBasedExpenseLineDetail class compared to ItemBasedExpenseLineDetail class.

**Comment by ej2** [comment]
I will get this fixed in the next release.

**Comment by ej2** [comment]
Resolved in 0.9.4 release
