### ISSUE TITLE
Estimate Class lacks Tracking No. Attribute

### ISSUE THREAD

**Issue by xqtive** [ej2/python-quickbooks#324]
Estimate Class does not have Tracking Number Attribute

**Comment by ej2** [comment]
I was unable to find a Tracking Number Attribute in the QBO [Estimate docs](https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/estimate#the-estimate-object). Could you provide more information on this?

**Comment by xqtive** [comment]
> I was unable to find a Tracking Number Attribute in the QBO [Estimate docs](https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/estimate#the-estimate-object). Could you provide more information on this?

It must have not been documented as a property of Estimate, but results of Estimates have trackingNum as its property, and it is also a form when creating an Estimate in the UI. 
![Untitled](https://github.com/ej2/python-quickbooks/assets/113651787/072e866d-a448-4348-bbea-a5ff8b3b2f0c)

**Comment by ej2** [comment]
Fixed in 0.9.6
