### ISSUE TITLE
Bill entity lacks VendorAddr as an attribute

### ISSUE THREAD

**Issue by xqtive** [ej2/python-quickbooks#332]
The bill class doesn't have VendorAddr as it attribute/property. Yeah, its not in the api documentation, but Bill responses has it.
![image](https://github.com/ej2/python-quickbooks/assets/113651787/c01c7c26-50fd-4443-ade8-a7b0c43a8fc6)

**Comment by ej2** [comment]
Fixed in 0.9.6
