### ISSUE TITLE
How to set CurrencyRef for Customer?

### ISSUE THREAD

**Issue by raccoon-in-munich** [ej2/python-quickbooks#338]
I am trying to create a customer with `Currency` but the `Customer` Object does not have `CurrencyRef` field. According to the [documentation](https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/customer#sparse-update-a-customer), it needs to be set during the sparse update. 

Is there a simple way to make a sparse update via the SDK? 

Is there an example of how to set `CurrencyRef` on Customer?

**Comment by raccoon-in-munich** [comment]
hey, I solved the problem. It seems like `CurrencyRef` was assignable in `Customer`. But because it was not initialized in `Customer` my autocomplete did not work.

Is it intentional that `CurrencyRef` is not initialized with a default value or is there a reason behind it?

 If you think it should be initialized I can create a PR to add it.

**Comment by ej2** [comment]
It was forgotten. I will add it in the next release.

**Comment by ej2** [comment]
Fixed in `0.9.7`
