### ISSUE TITLE
CurrencyRef reference value is incorrect

### ISSUE THREAD

**Issue by lisamburns** [ej2/python-quickbooks#344]
Repro steps:

- Find a currency and set its reference on a customer.
- Save the customer.
- I'd expect the customer's currency to be set to euros, but instead the API showed the customer's currency was set to GDP!

currency = QBCurrency.where("Code='EUR'", qb=self.qb_client)[0]
customer.currencyRef = currency.to_ref()
customer.save(qb=self.qb_client)

Looking at the code I think this is because the API docs state that value is supposed to be the 3-letter ISO code of the currency "EUR" rather than the ID of the currency object.

I was able to workaround this by running
currency = QBCurrency.where("Code='EUR'", qb=self.qb_client)[0]
currency_ref = currency.to_ref()
currency_ref.value = currency.Code # hack
customer.currencyRef = currency_ref
customer.save(qb=self.qb_client)

**Comment by ej2** [comment]
This is a case of the QBO documentation saying multiple things... [Customer docs](https://developer.intuit.com/app/developer/qbo/docs/api/accounting/most-commonly-used/customer) says `Id`. The [Multiple Currencies Use Case](https://developer.intuit.com/app/developer/qbo/docs/workflows/manage-multiple-currencies) says `code`. 

I will update it to use `code` in the next release.

**Comment by ej2** [comment]
Fixed in `0.9.7`
