### ISSUE TITLE
SalesItemLineDetail missing ItemAccountRef

### ISSUE THREAD

**Issue by zPugMan** [ej2/python-quickbooks#347]
The latest Quickbooks API spec allows for a a `ItemAccountRef` ref object.

ItemAccountRef
Optional
ReferenceType
Available with invoice objects, only, and when there is a linkedtxn of type ReimburseCharge for this object. When ItemRef.Id is set to 1, ItemAccountRef maps to the reimbursable charge account.

https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/invoice#full-update-an-invoice

v0.9.7 doesn't seem to support that reference object.

**Comment by ej2** [comment]
Added in 0.9.8.
