### ISSUE TITLE
Update intuit-oauth to latest version

### ISSUE THREAD

**Issue by yahel2410** [ej2/python-quickbooks#361]
Hi, 
I'm currently facing a dependency issue with the `python-quickbooks` package, which is preventing me from using the latest version of `intuit-oauth==1.2.6`. The current version constraints for intuit-oauth in python-quickbooks are:

```python-quickbooks (>=0.9.2,<0.9.8 || >0.9.8,<0.9.9 || >0.9.9,<0.10.0) requires intuit-oauth (1.2.4 || 1.2.5)```

The latest version of `intuit-oauth` contains an important [CVE fix](https://github.com/intuit/oauth-pythonclient/pull/49).
Could you please update the dependency version for intuit-oauth in the python-quickbooks package to support the latest version of intuit-oauth?

**Comment by yahel2410** [comment]
@ej2 Could please take a look at this?

**Comment by yahel2410** [comment]
Created PR for this - https://github.com/ej2/python-quickbooks/pull/362

**Comment by ej2** [comment]
Updated in release 0.9.10!
